language: java
jdk: oraclejdk8
before_install:
- chmod +x mvnw
deploy:
 provider: heroku
 api_key:
  secure: uJfzUj6M8wIcKBGbVlUHFkud6xkMbPByvXHySMJAOsIPtgo4r1fvdUVGf8AEX+c07Cbq0yqGzEeaHtuqMN0TaXiHRin1wmO4QJTsVv0KUOejfspkohNVeD3YLXJpwbN7coR1OGLcAj/1rTmp8iErhQdMm5j2xbzkFlE4XJZI9dkWWpbP5ySeI9j3vBOeNEQIH1dh5Z7DavN+gQL5lJwrLw5LiFq/GXcqgYjKgspWTsMeAku1DsODL78QfRJCPu+2Re2OM8Ov+Q53T3uNBUWZ2NUDb5MgEod3k3asMkzNmEmpUljJLSCfddC0FnGJ8lWBRNmMpmyYJ7gLmvOyXcxwJgCb7eHI0mosD0pNHAv7HQe5biAeqClrSqIqBM+mQMALeMnqgUg9hSPHJTWht5D3P7A+DnfumelqIXHLE9qDbiM00nR9Wb4/3f+fHmfk0ERjcc+4KhcTjp92DB98aBtJ0x7yIW2FB6GkVrcKLpdf9PP2RYO7gVdn7OHbepJ0CK434poVKB41HAZcBUoWh6fF8fCIDxygsaz9R5kzqhsdiUTDwxub1ckmAXZjJ3/sCZ7W3TehFlo1T7ZSBa7UqmHTL0PEBiLTGcWvEIm29hfF2lc5/AG7QuQlfpsCdpactuTSIsMr3llLBHOY1wXZjScUZMuWmyeXbKkL2DoYwqMn/kM=
services:
  - mysql