version: '3.7'

services:

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: xloads
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
